custombucket = "zendrix-app-artifacts"
customregion = "us-east-1"
databasehost = "zendrixdb.cc5iqq6wo1ld.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "Abhi1995"
s3database = "intellipaat"
kapp = "http://k8s-default-zendrixp-c038bd75d7-b5a8ec617c49553a.elb.us-east-1.amazonaws.com"
